/**
 * Regenerates src/abi/*.ts from the frozen Solidity interfaces.
 *   pnpm gen-abis        (requires `forge` on PATH)
 * Runs `forge inspect <Contract> abi --json` from the repo root (the parent of sdk/).
 * ERC20 and MakerVault ABIs are handwritten (src/abi/erc20.ts, src/abi/makerVault.ts) and not touched here.
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const inspect = promisify(execFile);
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, "..");
const repoRoot = resolve(sdkRoot, "..");
const outDir = join(sdkRoot, "src", "abi");

const targets: { contract: string; file: string; exportName: string }[] = [
  { contract: "IMontionsBook", file: "montionsBook.ts", exportName: "montionsBookAbi" },
  { contract: "IQuoter", file: "quoter.ts", exportName: "quoterAbi" },
  { contract: "IPriceOracle", file: "priceOracle.ts", exportName: "priceOracleAbi" },
  { contract: "IResolver", file: "resolver.ts", exportName: "resolverAbi" },
];

mkdirSync(outDir, { recursive: true });
for (const t of targets) {
  const { stdout: json } = await inspect("forge", ["inspect", t.contract, "abi", "--json"], {
    cwd: repoRoot,
    env: { ...process.env, FOUNDRY_OUT: join(sdkRoot, ".foundry", "out"), FOUNDRY_CACHE_PATH: join(sdkRoot, ".foundry", "cache") },
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  const abi = JSON.parse(json) as unknown[];
  const body =
    `// AUTO-GENERATED by sdk/scripts/gen-abis.ts from \`forge inspect ${t.contract} abi --json\`. Do not edit.\n` +
    `export const ${t.exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(outDir, t.file), body);
  console.log(`wrote src/abi/${t.file} (${abi.length} entries)`);
}
