// AUTO-GENERATED by sdk/scripts/gen-abis.ts from `forge inspect IQuoter abi --json`. Do not edit.
export const quoterAbi = [
  {
    "type": "function",
    "name": "fair",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "fairTick",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "probWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "volWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spotWad",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteBuy",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "yes",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "qty",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maxTick",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IQuoter.Quote",
        "components": [
          {
            "name": "filled",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cost",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "avgTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "worstTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "complete",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteSell",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "yes",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "qty",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "minTick",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IQuoter.Quote",
        "components": [
          {
            "name": "filled",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cost",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "avgTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "worstTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "complete",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "snapshot",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IQuoter.Snapshot",
        "components": [
          {
            "name": "seriesId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "info",
            "type": "tuple",
            "internalType": "struct IMontionsBook.SeriesInfo",
            "components": [
              {
                "name": "resolver",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
              },
              {
                "name": "expiry",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "status",
                "type": "uint8",
                "internalType": "enum IMontionsBook.Status"
              },
              {
                "name": "yes",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "yesId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "noId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "bidTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "bidQty",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "askTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "askQty",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "fairTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "probWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "volWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spotWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "title",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "snapshots",
    "inputs": [
      {
        "name": "offset",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct IQuoter.Snapshot[]",
        "components": [
          {
            "name": "seriesId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "info",
            "type": "tuple",
            "internalType": "struct IMontionsBook.SeriesInfo",
            "components": [
              {
                "name": "resolver",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
              },
              {
                "name": "expiry",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "status",
                "type": "uint8",
                "internalType": "enum IMontionsBook.Status"
              },
              {
                "name": "yes",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "yesId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "noId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "bidTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "bidQty",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "askTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "askQty",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "fairTick",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "probWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "volWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spotWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "title",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;
